### ISSUE TITLE
How to deploy and interact with pax contract?

### ISSUE THREAD

**Issue by qiluge** [paxosglobal/pax-contracts#1]
I followed steps to deploy pax token and proxy contract on ropsten network:
1. using remix compile pax token contract and deploy it without constructor arguments;
2. compile and deploy proxy contract with pax token contract addr as constructor argument;
3. invoke unpause of pax token contract;
4. set supplyController and law enforcement role of pax token contract;
5. increaseSupply of pax token contract;
6. add token and fix proxy contract addr on metamask chrom plugin;
7. metamask display 'PAX' symbol but balance is 0 and disable to transfer pax;

So, how can I use the proxy contract? Thanks.

**Comment by qiluge** [comment]
reference to https://github.com/paxosglobal/pax-contracts/blob/master/migrations/2_deploy_contracts.js

**Comment by qq29oo** [comment]
Thanks to @qiluge , nice solution!
