### ISSUE TITLE
Cool.

### ISSUE THREAD

**Issue by RyanKruse** [paxosglobal/pax-contracts#13]
> The total supply of PAX is backed by fiat held in reserve at Paxos.

So you've delegated an entire cryptocurrency to be solely controlled by one institution that has no external auditor verifying that such tokens are redeemable by the currency it is pegged to. Nice.

Honestly I scrolled through 22 shitcoins before I found this one, just swinging on by before I go to number 23.

**Comment by zimlokks** [comment]
> has no external auditor verifying that such tokens are redeemable by the currency it is pegged to.

Sure we can't verify it ourselves, but they do post monthly audits by a trusted third party. [see here](https://www.paxos.com/attestations/)

**Comment by gitteri** [comment]
Hi @RyanKruse, thanks for your concern. Paxos and PAX are approved and regulated by the New York State Department of Financial Services, ensuring the utmost of consumer protections. PAX is 100% backed by U.S. dollars held in FDIC-insured U.S. banks. Monthly audits by a top auditing firm attest to the supply and underlying U.S. dollars on a monthly basis.
