### ISSUE TITLE
Is this bug of your unit test ?

### ISSUE THREAD

**Issue by biigpongsatorn** [paxosglobal/pax-contracts#5]
Ref: https://github.com/paxosglobal/pax-contracts/blob/master/test/LawEnforcementTokenTest.js#L73

![image](https://user-images.githubusercontent.com/10693658/71350748-930a2000-25a4-11ea-8aef-cd1cec9d2808.png)

At line 73 should be 
```js
await this.token.approve(freezableAddress, approvalAmount, {from: otherAddress});
```
?

**Comment by lsharir** [comment]
@biigpongsatorn Thanks for pointing it out!
